# Setup
title: HyeonJin's GitBlog
description: welcome to hyeonjin's gitBlog :)        유레카프로젝트_깃블로그 제작하기
url: https://hyeonjin6530.github.io/
avatar: https://i.pinimg.com/564x/65/d0/29/65d0291efb4baa21dc76324d9e303c79.jpg
paginate: 5
permalink: pretty
cover_image: https://i.pinimg.com/564x/26/65/a0/2665a0c7ff8d769d2668289c27bbfaf7.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: hyeonjin6530
  card: summary
logo: logo.png
social:
  name: HyeonJin Hwang
  links:
    - https://www.instagram.com/h__jx_xn/
    - https://github.com/hyeonjin6530
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: HyeonJin Hwang
  url: https://github.com/hyeonjin6530
  email: alicehwang99@gmail.com

comments:
  provider: disqus
  disqus:
    shortname: hyeonjin6530

# Analytics
analytics:
  provider               : google
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : G-GLECBP0BSM
    anonymize_ip         : false 